name: Welcome

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    if: github.repository == 'adracea/WebGoat'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "SBOM With WhiteSource"
        run: |
          pip install ws-sbom-generator
          var=$(pip show ws-sbom-generator | grep Location: | sed -n -e 's/Location: //p')/ws_sbom_generator/sbom_generator.py
          python $var -u ${{secrets.WS_USER_KEY}} -k ${{secrets.WS_ORG_TOKEN}} -a https://saas.whitesourcesoftware.com -t json -s ${{secrets.WS_PROJECT_TOKEN}} -y product -o /home/runner/work/adracea/WebGoat/target/ -on webgoat-${{ steps.tag.outputs.tag }}.json